### ISSUE TITLE
Lubuntu Script

### ISSUE THREAD

**Issue by t8ert0t** [dagrha/pypia#1]
The script had an extra " -s " in the password line. This would cause the prompt to "jump" to the error stating that no password was entered after one typed in the username. Below it is written just as how the first lines are for the username, without the " -s " .

read_user_passwd( )
{
  echo -n "Please enter your PIA password. This gets added to your VPN config files: "
  read PASSWD
  if [ -z $PASSWD ]; then
    error "A password must be provided for the installation to proceed"
  fi
}

**Comment by dagrha** [comment]
Thanks for your patch.  In order to maintain that the password not be `echo`ed in the terminal, I've removed the `-s` as you suggest and also added another couple of lines. See comments at #2. Will close this issue for now since I've patched and verified it's working on Lubuntu 16.04. Thanks for reporting this bug!
