### ISSUE TITLE
How to set up on Solus?

### ISSUE THREAD

**Issue by tio-trom** [dagrha/pypia#36]
I am new to Solus, moving from Ubuntu (so I'm still learning), but how do I set this up on Solus?
```

tio@trom ~ $ pip install pypia
bash: pip: command not found
tio@trom ~ $ eopkg install pypia
Program terminated.
You have to be root for this operation.
Please use 'eopkg help' for general help.
tio@trom ~ $ sudo eopkg install pypia
Password: 
System error. Program terminated.
Repo item pypia not found
Please use 'eopkg help' for general help.
Use --debug to see a traceback.
tio@trom ~ $ pypia -i
bash: pypia: command not found
tio@trom ~ $ 
```

**Comment by dagrha** [comment]
Hi TROMsite, `pip` is the python package manager-- it is used to install python packages. The first error you show (`bash: pip: command not found`) seems to indicate that pip is not installed or is not in your path.

A couple recommendations to try:
1) you could try to invoke pip by running `python -m pip install pypia`. Note that you may need to use `python3` instead of `python`-- I'm not sure if solus os uses python 2.7 or python 3+ by default.
2) if that doesn't work and indeed pip is not installed, you can try to use the os package manager to install it. Something like `eopkg install pip` or `eopkg install pip3`-- you'll have to consult Solus documentation or forums. If that works, you could then possibly use the `pip install pypia` command.
3) If none of the above work, you can clone this repo, cd to the directory where `pypia.py` lives and invoke the script directly (`python pypia.py -i`). Note that with this option, `pypia` would not be added to your PATH, so you could not invoke simple `pypia` at the terminal, but you'd get the VPN routes in the NetworkManger applet.

Please let me know if you get it working and how. Cheers.

**Comment by tio-trom** [comment]
Thank you very much, it worked after installing pip via Solus repositories. Awesome! Thank you!
