### ISSUE TITLE
Certificates Out of Date?

### ISSUE THREAD

**Issue by kgillibrand** [dagrha/pypia#5]

**Comment by dagrha** [comment]
Thanks for bringing this up. In the old script from PIA, the cert has not been rotated yet, so I'll have to dig around to find the new cert.

**Comment by Favorablestream** [comment]
The downloads for Openvpn configurations each contain 2 certificates though I'm not sure which one you would need. Maybe one of those would help.

Standard (RSA-2048): https://www.privateinternetaccess.com/openvpn/openvpn.zip

Strong (RSA-4096): https://www.privateinternetaccess.com/openvpn/openvpn-strong.zip

**Comment by dagrha** [comment]
I think we are ok actually. 

After looking into this a bit more, I _think_ the way this works is that the `ca.crt` file created by the script is really just the certificate authority file, in other words it's the public key used to verify the VPN connections. So, when the client initiates a connection to a remote PIA server, it uses that public key to securely send information about the connection to the server, then the server sends back the certificate (hopefully it sends the newly rotated certificate!) to be used for the VPN session, which is then verified using the `ca.crt` signature. It's a wee bit more complicated than that, but that's the gist from what I can gather.

Since this doesn't appear to be an issue after all, I am going to close this for now. But we can always re-open if it turns out I am mistaken about this. Thanks again for bringing it to my attention.

**Comment by Favorablestream** [comment]
Sure thing, thanks for checking.
